### ISSUE TITLE
[PROPOSAL] split tables on mobile devices/fix header and first column

### ISSUE THREAD

**Issue by howardchung** [odota/web#1378]
A proposal to split wide tables for mobile devices:

Currently we deal with wide tables by making them scrollable to the right, which works but is suboptimal because the leftmost column (like the hero column) gets hidden and it becomes difficult to tell which row the data goes with.

This makes large tables almost unusable on mobile devices:
https://www.opendota.com/heroes/public

We could extend our column definitions to include a field called `group` and pass an object to each `Table` component that maps each group name to a display name, e.g.

A sample columndef:
```
const columns = [{ field: 'kills', group: 'kda'}, { field: 'deaths', group: 'kda' }, { field: 'assists' , group: 'kda'}, { field: 'gold_per_min': group: 'farm' }]
```

Then we could have an object mapping each key name to a display name:
```
const groups: { kda: strings.kda, farm: strings.farm };
```

The table would detect when it is being rendered on a small screen and when it does, automatically create a dropdown menu (rendered above the table) that has as options all of the group names in the table.  Only one group would be selected at a time, and the table only renders the columns with a `group` name matching the currently selected value in the dropdown.

In the above example, the group names would be 'kda' and 'farm'.

**Comment by GravityMsc** [comment]
I have an advice: 
  Can we fix the thead and scroll the tbody. And the same time, we fix the hero columns and scroll-x of the table. if width is not enough,hide heros' name.

there is an [example](https://ant.design/components/table/#components-table-demo-fixed-columns-header) of Ant Design

**Comment by howardchung** [comment]
Hmm, I do like that solution.  Can we implement similar logic on the material-ui table?

**Comment by GravityMsc** [comment]
I need to learn about material-ui. I am not familiar with it.
This need some time to do. I try it in my rest time, and you can highlight this issue to call our contributors to attemt it.

**Comment by JaydenIvanovic** [comment]
I'm happy to attempt the above solution with the material-ui table. Have you put any work into this so far?

**Comment by GravityMsc** [comment]
@JaydenIvanovic not yet. Recently I don't have enought time to do this.

**Comment by JaydenIvanovic** [comment]
I should have some free time the next couple of days so I'll take a look and see what I can do.

**Comment by JaydenIvanovic** [comment]
I have pushed up a branch (feature/1378-fixed-column-table) which implements the aforementioned solution at the /heroes/public route. I wouldn't mind getting some feedback UX wise before proceeding to clean it up / ready it for a PR (if you would prefer me to make the PR straight up let me know). 

It would probably also be worth going through the application and seeing where large tables exist and assessing whether the same solution is applied to them as well.

One remaining thing I need to do is work out how to keep the different colored rows as you scroll down the page. At present this is done via making the table transparent to let the background gradient "bleed through" (I have temporarily disabled this on my branch). Given the heroes column is fixed by absolutely positioning a second table (with the heroes column as its sole source of data) over the top, this causes you to see the data behind it as you scroll.

**Comment by howardchung** [comment]
Go ahead and make a PR, that makes netlify upload a preview which makes it easy to review the changes without running the PR locally.
