### ISSUE TITLE
Time to remove solo and estimated MMR?

### ISSUE THREAD

**Issue by TrentBartlem** [odota/web#1404]
It's old and outdated. The estimated MMR would, _at best_ be replaced with an estimated medal.

**Comment by howardchung** [comment]
I'm not sure if Valve plans to enable the "historical MMR" that can be publically displayed once per season.  If so, there'd still be some value to displaying MMR.  Otherwise we could probably remove it.

**Comment by TrentBartlem** [comment]
Can always hide it until then

**Comment by Bumrang** [comment]
Dotabuff still has a way to grab the MMR somehow, as it's updating for me, so there must be a way to do it.

**Comment by howardchung** [comment]
Account ID?

**Comment by Bumrang** [comment]
35829474

**Comment by howardchung** [comment]
Hmm, it looks like your account still has MMR available.  I think it's there if you had it displayed and never removed it, but not available for new players to display.  I've re-enabled MMR updates if the data is available, let me know if it updates after your next ranked match.

**Comment by howardchung** [comment]
Plan is to revisit this when the next ranked season starts.  If Valve allows players to display their actual MMR, we can get at least data every 6 months.  If not, we should probably remove it.

That reset should be in May.

**Comment by KKire** [comment]
Can you hide it until then? Right now it's stuck and not updating anymore. Since they made medals and you removed your mmr from your profile, it doesn't update anymore.
I suggest you just hide it from profiles or add option to hide it and reenable or remove when/if they change something next season.

**Comment by howardchung** [comment]
It's actually updating for a small percentage of users.

Since we're only a couple of months out, I think we can wait until then to see what Valve does.

At that point we can decide whether the best course of action is to label the data with the date it was collected, or remove it from the header (leaving the MMR graph the same)

**Comment by KKire** [comment]
It's only updating for those who kept the Solo and party on their profile when you hover over them. If you removed it, you can't re select it anymore. At least an option for hiding it (like on dotabuff) would be nice. For example, my MMR is bit updated for over a year ago (on both, open dota and dotabuff) and I hid it on dotabuff but there is no option for it on open dota.

**Comment by IrenGree** [comment]
Guys, we really need to fix it. It is not actually now, because mmr system has been reworked.

**Comment by KKire** [comment]
@IrenGree they are waiting for season to end and valve might add that back. If nothing is changed for season 2, they will remove it as far as I understood before.

**Comment by howardchung** [comment]
well, it's June and Valve hasn't started the new season yet.  I'll give them a few more weeks

**Comment by aeosynth** [comment]
new season is live :tada:

**Comment by howardchung** [comment]
OK, let's remove solo/party/estimated MMR from display since it doesn't look like Valve will provide a way to display it.
