### ISSUE TITLE
Estimated MMR

### ISSUE THREAD

**Issue by leodej** [odota/web#1423]
The estimated MMR is a farce, It was estimated at 3994 and the same came in 2174 an absurd difference!

**Comment by howardchung** [comment]
Estimated MMR accuracy will vary based on many factors depending on who you play with and whether you play ranked or unranked.  In most cases it should pretty close (within 500 points), but outliers will exist (such as your case).

MMR estimation will get less and less accurate as time goes on though since public MMR was removed.  We may just want to hide the estimate in the UI.

**Comment by andyklimczak** [comment]
I need to double check, but I do believe there is an MMR value inside the dota2 client (profile -> stats). Not sure if it's exposed or not

**Comment by Argn0** [comment]
@andyklimczak  It's not exposed.
