### ISSUE TITLE
Story showing wrong first blooded hero

### ISSUE THREAD

**Issue by SliVee** [odota/web#1424]
https://www.opendota.com/matches/3677057975/story

In that match Earthshaker died first mid lane to Shadow Fiend. Story tells that Phantom Lancer died which is wrong. You can check replay or here is the screenshot of it happening:
![first_blood](https://user-images.githubusercontent.com/35404027/34908284-be4891a4-f895-11e7-956f-ef38e1adfb84.png)

**Comment by howardchung** [comment]
@mdiller 

According to this:
https://www.opendota.com/matches/3677057975/log

The first blood event was recorded, but not a kill event (probably because a creep got the actual last hit, but the game credited the kill to SF anyway).  IIRC there is a "slot" field in the first blood object that indicates which player was killed, perhaps we should use that for the story instead of the first kill event?

**Comment by mdiller** [comment]
If I remember correctly, there were issues with using "slot" when I implemented that feature. It looks like it has probably been fixed now though so I'll make that change yeah sure.

**Comment by mdiller** [comment]
I submitted a pull request #1427. It looks like it is actually "key" instead of "slot". I left in a failsafe to use the old method if "key" is undefined or null.
