### ISSUE TITLE
Paginated Tables save state when changing Data

### ISSUE THREAD

**Issue by gar-stauffer** [odota/web#1460]
When switching from the Heroes tab to the Matches tab under teams, the table saves the same page from the previous tab. This can cause some issues with displaying the data, pictures attached.

When viewing matches, there's up to 52 pages, because Liquid has so many games.
![highpagematches](https://user-images.githubusercontent.com/16960404/36709648-f2e32694-1b46-11e8-8de0-464bc1509098.png)

After being on Page 52 of Matches, clicked the "Heroes" tab. Table appears to still be trying to load page 52, even there's only 6 pages.
![highpageontablewithless](https://user-images.githubusercontent.com/16960404/36709649-f2eb03f0-1b46-11e8-8ab2-1a302659dcbd.png)

**Comment by spudde123** [comment]
Hey, I think this specific issue can be fixed in a single line. In Team/index.jsx componentWillUpdate function is missing the check for whether location.key (the tab) has changed. It doesn't end up updating the table data properly when the tab changes.

Instead of
`if (this.props.match.params.teamId !== nextProps.match.params.teamId)`
it should have
`if (this.props.match.params.teamId !== nextProps.match.params.teamId || this.props.location.key !== nextProps.location.key)`

With this change it defaults to page 1 of the table when the tab is changed, similarly as in individual player pages

**Comment by spudde123** [comment]
Ah, I didn't notice this behavior when working on the page originally. In the individual player pages for example (where this behavior could also happen), it doesn't seem to because the pages update their data whenever the tab has changed and the tables default to page 1.

Adding `if (this.props.match.params.teamId !== nextProps.match.params.teamId || this.props.location.key !== nextProps.location.key)` in place of https://github.com/odota/web/blob/981e0ed8b83d785cde3c25d54892fdf5b34d3c1e/src/components/Team/index.jsx#L26 would fix it but it doesn't seem ideal because all the data is fetched already (for displaying the Overview page). While this would fix the UI issue, it would result in the same data request being remade all the time.

**Comment by spudde123** [comment]
Actually perhaps the resetTableState prop could be useful for the Tables. Need to look around the Table code a bit to see how things precisely work

**Comment by gar-stauffer** [comment]
Yeah, I think there's probably a one line change somewhere to reset the specific PaginatedTable attributes within `Table/index`. It seems like Table has knowledge of its sub-class (e.g. it is in charge of pagination and actions for forward and back-clicks), so it might be worth trying to extract all of that into the PaginatedTable file in this process... or maybe not.

Are you going to keep looking at this @spudde123 ?

**Comment by spudde123** [comment]
Yeah I can look into it tomorrow

**Comment by spudde123** [comment]
I'm not that experienced with the inner workings of React but it seems to me that because the Matches and Heroes tabs are identical as far as their components go with just the props being different, React is reusing the components if you switch from one tab to the next. If as a test you wrap one of them with `<div></div>` for example, the behavior disappears because React isn't trying to reuse the same Table component anymore. Also if you switch to some other tab in between, it works fine as the same table isn't getting reused.

Currently the Table component has the following clause for resetting the table:
https://github.com/odota/web/blob/7c7127f7ddc6d4d61420e2f016a769595a50e67e/src/components/Table/Table.jsx#L91-L94
The resetTableState prop seems to be only used in the Explorer atm. But I am a bit unsure whether this if clause is needed, or if it would be desirable to simply reset the table state whenever new props come.

**Comment by howardchung** [comment]
Yeah, I guess let's try resetting table state when the props change.  For safety let's just keep it as is and pass the resetTableState prop in the teams tables
