### ISSUE TITLE
match crash on underhollow game

### ISSUE THREAD

**Issue by howardchung** [odota/web#1793]
https://www.opendota.com/matches/4079228298

```
TypeError: Cannot read property 'gold_delta' of undefined
    at main.ff1f8639.js:1
    at Array.map (<anonymous>)
    at o (main.ff1f8639.js:1)
    at Array.map (<anonymous>)
    at o (main.ff1f8639.js:1)
    at s (main.ff1f8639.js:1)
```

**Comment by anamritraj** [comment]
This is happening because `player.player_slot % (128 - 5)` is changing from `0` to `10`. But `10` is not a valid index for the `tf.players` array. 

https://github.com/odota/web/blob/5b1691e34f6c2a611bea9e535e845a668768ae82/src/actions/transformMatch.js#L43-L46

I am new here and can't properly understand why `player.player_slot` needs to be `mod` with `128-5`

**Comment by anamritraj** [comment]
Thanks. I will be fixing this.
