### ISSUE TITLE
Timing Bug on Draft Tab

### ISSUE THREAD

**Issue by markcaldropoli** [odota/web#2104]
On the draft tab of a Captain's Mode game, it is incorrectly showing the time for the first ban of the draft. I attached a few screenshots below.

[Example 1:](https://www.opendota.com/matches/4674427056/draft)

<img width="743" alt="Screen Shot 2019-04-20 at 11 47 07 PM" src="https://user-images.githubusercontent.com/22227236/56465203-1268a380-63c7-11e9-9ce1-e362b90a6327.png">

[Example 2:](https://www.opendota.com/matches/4674338931/draft)

<img width="730" alt="Screen Shot 2019-04-20 at 11 47 46 PM" src="https://user-images.githubusercontent.com/22227236/56465199-0c72c280-63c7-11e9-837c-55d51690c662.png">

[Example 3:](https://www.opendota.com/matches/4674236306/draft)

<img width="753" alt="Screen Shot 2019-04-20 at 11 48 06 PM" src="https://user-images.githubusercontent.com/22227236/56465204-1694c100-63c7-11e9-844d-eebe00bb8ab3.png">

**Comment by howardchung** [comment]
Probably the replay format changed somewhere, we'll have to look at the replay contents.

**Comment by howardchung** [comment]
https://github.com/odota/core/blob/master/processors/processDraftTimings.js

**Comment by lancebendo** [comment]
> Probably the replay format changed somewhere, we'll have to look at the replay contents.

Hi! I tried to debug this issue and I found out that in processDraftTimings.js, the calculation of draft timings is (time of last draft minus to time of current draft) and if it is calculating the first draft, it should be (time of the beginning of draft stage minus time of current draft). But instead, it's just passing the time of current draft that's why we're getting this issue of having -700s or more value instead.
https://github.com/odota/core/blob/085ceed8d9b26416fc554205832fe650ddc181b7/processors/processDraftTimings.js#L49

I think the solution for this is have the odota/parser record the start time of draft stage and pass it to the processDraftTimings.js to calculate the time of first draft correctly. I tried to run the Clarity Analyzer and I think I find a way to record the start time in case it is not yet implemented in odota/parser. I'm just wondering how can I run the odota/parser to my local machine and make the parser service call it instead of the production odota/parser so that I can make code changes and test it locally?

**Comment by howardchung** [comment]
I believe you can clone the odota/parser repo, make the edit in the Java code, then rebuild the docker container with `docker build . -t odota/parser`

Then try restarting your docker-compose stack and it should run your local version instead

If that doesn't work there might be a few other options

**Comment by howardchung** [comment]
You might have to delete the old odota-parser container

**Comment by lancebendo** [comment]
Okay I'll give it a try. Thanks!
