### ISSUE TITLE
Ability Build table - level 30 heroes have incorrect talents

### ISSUE THREAD

**Issue by ahi-el** [odota/web#2460]
Currently, when a hero gets to level 30, the table will have 3 extra talents for levels 21,22,23
https://www.opendota.com/matches/5253438125

![image](https://user-images.githubusercontent.com/37062459/75049170-699d4000-54d2-11ea-88ac-9085a0662e2f.png)

This is also missing (for some reason) one of the talents (currently only 7 talents instead of also having a level 24 talent)

Possible solutions:
1) Not display the extra talents (I'm leaning towards this one, should be easiest to do and reflects the actual build of the hero)
2) Display talents all the way up to level 30 (and then at level 30 just have a '+' or something noting that it has been achieved)
3) Add the 8th talent at level 24 (don't think that this is the correct fix but it would be better than current)

**Comment by howardchung** [comment]
I went with the first approach. The data by default is added on as 4 extra abilities at the end of the array. These used to line up with the levels, but since talents aren't added in consecutive levels we mapped the actual level to the array position. Since we didn't map the last few abilities they defaulted to the array position (21-23). 20 did not show up because we already had something in position 20.
