### ISSUE TITLE
Neutral item icon slot displays differently from regular items

### ISSUE THREAD

**Issue by deepakgsingh** [odota/web#2541]
Neutral item icon slot in Overview page displays differently from regular items. The scalings seem different as attached.

![image](https://user-images.githubusercontent.com/41690483/79970937-4df1ee00-84b1-11ea-817e-f84d03fe4019.png)

**Comment by howardchung** [comment]
Looks like in @Argn0 's original implementation the images are assumed to be squares but they're actually rectangular:
https://github.com/odota/web/commit/7b34253a8e9a8765f54649fb3626b2d776a77c21

We can resolve by tweaking the container height to 22px and removing the 30px CSS on the neutral class.

This results in oval-ish item photos but since the originals aren't square idk if there's a better method. Maybe we could crop the sides

**Comment by deepakgsingh** [comment]
The in-game client seems to take the latter approach of cropping the sides.

![image](https://user-images.githubusercontent.com/41690483/79982676-51db3b80-84c4-11ea-9337-cd1c4a0e9002.png)

**Comment by Argn0** [comment]
I fixed the weird oval shape. I hope this solves the issue.
