### ISSUE TITLE
MMR bot detection and rampages

### ISSUE THREAD

**Issue by albertcui** [odota/web#887]
Posting from reddit message:
> Hello.
> I was wondering if you guys had any plans on creating a way to view games played against MMR farming bots. I don't know how difficult that might be but I don't imagine it to be too difficult. Just looking for which matches have players with almost no items and have a large number of deaths with little to no kills or assists.
> This feature would make it very easy to find out who is abusing bots for personal gain.
> I was also wondering if there is a way to view how many rampages a person has done and which games they occurred in.
> Personally, I have a friend that attempts to get as many rampages as he can against bots to make his profile look better.
> Anyways, I love the website and I am a proud plus member. Thank you very much for everything you have done.
> Thank you.

**Comment by howardchung** [comment]
@Crazy-Duck has done some work on identifying matches with anomalous stat counts, and we could probably reuse some of it in odota/core to find these matches.

Counting rampages:
We have the data already in player_caches, so would just be a matter of summing them up and displaying (maybe in the Counts tab).  Sample API call:
https://api.opendota.com/api/players/88367253/matches?project=multi_kills&limit=10

Finding matches with rampages:
This would require a filter to be added.  Also doable, but a bit more work than just counting them, and we probably need to think about how the filter should be added (not sure if adding a new box for each multi kill type is good UX)

**Comment by Crazy-Duck** [comment]
The approach I used was one based on anomaly detection. Basically I identified a few parameters that were decently Gaussian in nature (with limited skew) and searched for outliers via machine learning. Based on that data it was very easy to obtain a set of matches that contained abuse like:
- battle pass exploitation
- MMR boosting
- ...
This approach still had a very low false positive rate (typically extremely long games with enormous amounts of kills etc), which could however be 100% eliminated by looking for repeat offenders. If you were to make a list of players and recorded how many times they occurred in the as abuse identified games, you could filter out the innocents. The biggest issue with this however, is that the overwhelming majority of bot accounts and MMR boosters have their profiles set to private, which causes them to show up as anonymous players (which are all mapped onto the same account ID) in the match details. In the end, the only abuse you'd be able to identify without having access to Valve's data are the battle pass abusers, since they tend to be normal players who often have their profiles public.
